// Stable catalog choices used by the photo diagnosis model and the report UI.
// Outfit IDs point to the existing inspiration image IDs in page.js.
export const REPORT_HAIR_CATALOG = [
  "微分碎盖",
  "龙须背头",
  "三七侧背",
  "括号刘海",
  "美式前刺",
  "短碎发",
  "中分",
  "逗号刘海",
  "二八侧背",
  "自然纹理",
  "港风背头",
  "短发微分",
  "中分纹理",
  "三七纹理",
  "摩根前刺",
  "长发狼尾",
  "羊毛卷",
  "锡纸烫",
  "韩式烫",
  "烟花烫",
  "法式烫",
  "钢夹前刺",
  "钢夹烫",
  "莱斯利卷",
  "造型烫",
  "蝴蝶烫",
  "束状纹理",
  "摩根烫",
  "碎盖前刺",
  "中式前刺",
  "韩式前刺",
  "侧背前刺",
  "立体前刺",
  "上扬前刺",
  "纹理前刺",
  "中分前刺",
  "凌乱前刺",
  "气垫烫",
  "纹理烫",
  "漫画烫",
  "摩根碎盖",
  "长发纹理",
  "凌乱背头",
  "懒惰卷",
  "纹理三七",
  "日系纹理",
];

export const REPORT_OUTFIT_CATALOG = [
  {
    id: "outfit-1",
    name: "城市通勤·藏蓝外套",
    items: "藏蓝外套、浅色内搭、卡其直筒裤",
    palette: "藏蓝、米白、卡其",
    scene: "城市通勤、日常见面",
  },
  {
    id: "outfit-2",
    name: "清爽通勤·浅蓝衬衫",
    items: "浅蓝衬衫、黑色长裤、简洁鞋款",
    palette: "浅蓝、黑、白",
    scene: "通勤、校园、日常约会",
  },
  {
    id: "outfit-3",
    name: "夏日周末·藏蓝短袖",
    items: "藏蓝短袖上衣、白色短裤、低帮休闲鞋",
    palette: "藏蓝、白、灰",
    scene: "周末出行、夏日休闲、户外活动",
  },
  {
    id: "outfit-4",
    name: "松弛日常·白衬衫卡其裤",
    items: "宽松白衬衫、卡其长裤、低帮鞋",
    palette: "白、卡其、浅棕",
    scene: "日常出行、咖啡馆、周末",
  },
  {
    id: "outfit-5",
    name: "简约街头·黑色上衣",
    items: "黑色短袖、灰色宽松长裤、运动鞋",
    palette: "黑、灰、白",
    scene: "日常街拍、休闲出行",
  },
  {
    id: "outfit-6",
    name: "清爽休闲·蓝衬衫白裤",
    items: "蓝色衬衫、白色长裤、简洁休闲鞋",
    palette: "蓝、白、浅灰",
    scene: "春夏出行、日常见面",
  },
  {
    id: "outfit-7",
    name: "干净日常·浅色上衣牛仔裤",
    items: "浅色上衣、蓝色直筒牛仔裤、白鞋",
    palette: "白、浅蓝、牛仔蓝",
    scene: "日常出行、校园、周末",
  },
  {
    id: "outfit-8",
    name: "夏日轻松·白T短裤",
    items: "白色短袖、浅色短裤、低帮休闲鞋",
    palette: "白、浅灰、蓝",
    scene: "夏日休闲、旅行、户外",
  },
  {
    id: "outfit-9",
    name: "清爽基础·白T蓝裤",
    items: "白色短袖、蓝色直筒裤、简洁鞋款",
    palette: "白、蓝、黑",
    scene: "日常通勤、校园、街拍",
  },
  {
    id: "outfit-10",
    name: "松弛街头·深色上衣",
    items: "深色上衣、卡其宽松长裤、休闲鞋",
    palette: "黑、卡其、灰",
    scene: "城市休闲、周末出行",
  },
  {
    id: "outfit-11",
    name: "清爽层次·蓝白条纹",
    items: "蓝白条纹上衣、浅色长裤、轻便鞋款",
    palette: "蓝、白、灰",
    scene: "春夏日常、校园、咖啡馆",
  },
  {
    id: "outfit-12",
    name: "夏日街头·宽松短袖",
    items: "宽松浅色短袖、牛仔短裤、休闲鞋",
    palette: "白、蓝、红色点缀",
    scene: "夏日街拍、旅行、户外",
  },
];

export function outfitCatalogPrompt() {
  return REPORT_OUTFIT_CATALOG.map((item) =>
    `${item.id} | ${item.name} | 单品：${item.items} | 配色：${item.palette} | 场景：${item.scene}`,
  ).join("\n");
}
