export const MAIN_PLANS = [
  {
    id: "trial",
    name: "体验卡",
    price: "¥9.9",
    credits: 8,
    membershipDays: 30,
    hook: "先看看 AI 能把你变成什么样",
    tier: "小帅档 · 先试水",
    shots: "约 4 张标准 1K 展示面",
    expires: "额度永久有效",
    popular: false,
    description: "AI 拍出来啥样，自己看一眼再决定要不要加钱。不满意也没亏。",
  },
  {
    id: "high",
    name: "标准卡",
    price: "¥39.9",
    credits: 36,
    membershipDays: 30,
    hook: "日常展示面够用，要更好就上旗舰",
    tier: "大帅档 · 效果出众",
    shots: "约 9 张高清 1K 展示面",
    expires: "额度永久有效",
    popular: true,
    description: "9 成用户选这档。一次配齐约会展示面 + 社交头像 + 日常照，性价比最高。",
  },
  {
    id: "flagship",
    name: "旗舰卡",
    price: "¥99",
    credits: 90,
    membershipDays: 60,
    hook: "要精修级、要人长得像，直接上",
    tier: "顶帅档 · 精修质感",
    shots: "约 15 张旗舰 1K 展示面",
    expires: "额度永久有效",
    popular: false,
    description: "人脸一致性最好，光影背景全拉满，长期打造高质量个人形象。",
  },
  {
    id: "refill",
    name: "次数补充包",
    price: "¥19.9",
    credits: 15,
    membershipDays: 0,
    hook: "会员还在，次数不够了？加这个",
    tier: "档位跟随当前会员",
    shots: "按当前档位继续生成",
    expires: "额度永久有效",
    popular: false,
    description: "会员期没过、次数不够用的救急包。不改变档位，只补次数。",
  },
];
